### ISSUE TITLE
symbol repetition

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Sheesh-Compiler#3]
### **ISSUE: code bug when detecting negative values for whole literal**

`whole num= (-20)#`

will output a lexeme table of 
| LEXEME | TOKEN|
|--------|--------|
| whole | Keyword |
| num | Identifier |
| = | Operator |
| (-20) | Whole |
| ( | Symbol |
| ) | Symbol |
| # | Symbol |

_( and ) is repeated_

**Comment by remoo69** [comment]
fixed with re.escape
